spring.application.name=kbeauty

# DB 연결 설정 (MySQL/MariaDB 예시)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/kbeauty?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=12345

# JPA 설정
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSON 응답 시 한글 깨짐 방지
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true