spring.application.name=kbeauty

# DB 연결 설정 (MySQL/MariaDB 예시)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://db-server-pj.mysql.database.azure.com:3306/kbeauty?useSSL=true&serverTimezone=Asia/Seoul
spring.datasource.username=testuser
spring.datasource.password=qwert123!

# JPA 설정
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSON 응답 시 한글 깨짐 방지
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true